
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Thu Jul 11 09:51:35 GFT 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VALOR = 11;
  public static final int WHERE = 9;
  public static final int INTO = 10;
  public static final int UPDATE = 4;
  public static final int SET = 8;
  public static final int EOF = 0;
  public static final int DELETE = 5;
  public static final int error = 1;
  public static final int SELECT = 2;
  public static final int FROM = 6;
  public static final int VALUES = 7;
  public static final int INSERT = 3;
}

